### ISSUE TITLE
Error while downloading an audio 

### ISSUE THREAD

**Issue by Yashwin12** [przemyslawpluta/node-youtube-dl#208] opened 2018-07-20 13:42 UTC
WARNING: nOgF4TN7Gkk: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.
ERROR: ffprobe or avprobe not found. Please install one.

It throws error like this and installing doesnt fix the issue for this. File is getting downloaded in m4a and .webm extension not in mp3 extension as per the expectation.

**Comment by yafp** [comment] 2020-01-23 20:51
@Yashwin12 
you should add the command which was causing the error - to make it reproduceable for others.

**Comment by Kikobeats** [comment] 2020-01-24 18:38
Closing since the issue is poorly documented for addressing it – Thanks @yafp!

**Closed by Kikobeats** 2020-01-24 18:38 UTC
