### ISSUE TITLE
Can't get stream connection on Linux and handling foreign characters in titles.

### ISSUE THREAD

**Issue by Shrekie** [przemyslawpluta/node-youtube-dl#203] opened 2018-05-14 17:34 UTC
This is how I grab a stream connection and it seems to be working great.

``` javascript
ytdl.exec(url, ['-f best', '-s', '-g'], {}, function(err, output) {
   var stream = output[0];
});
```

However when it comes to one video and I can't really pinpoint why, the request to the URL fails. 
But it does not do so on localhost Windows only on the live Linux environment. 

> https://www.youtube.com/watch?v=HQgaCVT9Bw8

Must note that to get youtubedl working locally I use the altered .exe which might be the only discrepancy between the live and local environment.

This is how I grab the title of a video, doing it with the video above for example yields a null value because it contains purely foreign characters.
``` javascript
ytdl.exec(url, ['-s', '-e'], {}, function(err, output) {
   var title = output[0];
});
```
Japanese character rendering might be a feature request though.

**Comment by yafp** [comment] 2020-02-13 08:20
@Shrekie 
Is this still valid?

If i am running an youtube.exec cmd to download this url it works for me without issues

**Comment by Kikobeats** [comment] 2020-02-13 10:01
closing since @yafp verified it's working fine nowadays and the issue is so old.

Happy to open again if this is a real problem 👍

**Closed by Kikobeats** 2020-02-13 10:01 UTC
