### ISSUE TITLE
Command failed when i specified both video and audio format

### ISSUE THREAD

**Issue by perezcato** [przemyslawpluta/node-youtube-dl#304] opened 2020-04-15 08:44 UTC
Command failed anything i added both the video and audio format 
this is the output of the error 

> --------------------------------------------------------------------------------------------------------

**(node:21565) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at processData (/home/derrick/projects/youtube-cli-dowloader/node_modules/youtube-dl/lib/youtube-dl.js:42:17)
    at getInfo (/home/derrick/projects/youtube-cli-dowloader/node_modules/youtube-dl/lib/youtube-dl.js:106:9)
    at done (/home/derrick/projects/youtube-cli-dowloader/node_modules/youtube-dl/lib/youtube-dl.js:259:12)
    at done (/home/derrick/projects/youtube-cli-dowloader/node_modules/youtube-dl/lib/youtube-dl.js:25:12)
    at /home/derrick/projects/youtube-cli-dowloader/node_modules/universalify/index.js:23:46
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:21565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

> ----------------------------------------------------------------------------------------------------------------
with following code 
`const videoDownloading = youtube('https://www.youtube.com/watch?v=j5-yKhDd64s',
                [`-f 160+140`],
                { cwd: path.join(getRootDir(),'.youtube-downloader')});`

**Comment by luizcieslak** [comment] 2020-04-17 02:27
I think this is a duplicate of #221 .

**Comment by perezcato** [comment] 2020-04-18 19:03
okay

**Closed** 2020-04-21 01:02 UTC
